services:
  - type: web
    name: timebank
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: timebank-db
          property: connectionString

databases:
  - name: timebank-db
    databaseName: timebank
    user: timebank
